### PR TITLE
fix typo in `./docs/md/account/blog.md`

### PR DESCRIPTION
**Pull request by im-coder-lg**
noticed a typo, forked and fixed it.
The typo was:
You typed `compormised` instead of `compromised` which is a typo here. I noticed it and gave a fix here. Is this good?

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Typo was in security section

**Comment by im-coder-lg** [comment]
@must and @loreanvictor check this when you are free

**Comment by loreanvictor** [comment]
thanks, looks good to me.

**Review by loreanvictor — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Thanks!😀

**Pull request merged**
