### PR TITLE
Clean up and report page changes correctly to ga

### PR DESCRIPTION
**Pull request by must**

### CODE REVIEW

**Comment by TysonMN** [comment]
Was there something wrong with the previous code?

**Comment by must** [comment]
So from my tests the url does not get updated with page reloads. It has to be updated through the ga tracker. [More info here](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications).

You can test this on the Realtime -> Content section on the Google Analytics dashboard where you can see both the title and URLs being navigated to by a user in real-time. With your previous implementation it looked to me like the initial URL is always reused while the title was getting updated when loading new pages (navigating on the SPA). So I reimplemented it according to their documentation on single page applications ([same as the previous link](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications)). I hope this helps!

**Comment by TysonMN** [comment]
Ah, you are correct.  Great catch.

Another way to see this is using Google's Tag Assistant extension.  Clearly I didn't look closely enough at the data.

2020-09-09_11-49-02_286_chrome

**Comment by TysonMN** [comment]
I fixed that problem in [this commit](https://github.com/bender2k14/tyson-williams-blog/commit/8694b3cf9c10243455898db2b30f1008a6ca4696).  Thank you so much for noticing this and telling me about it.

2020-09-09_20-04-51_287_chrome

**Comment by must** [comment]
@bender2k14 Awesome :) I'm glad it helped. Looking forward to getting this as a codedoc plugin.

**Pull request merged**
